name: "Build & Test"

on:
    pull_request:
      branches:
        - master

jobs:
    TestBuild:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Install node
              uses: actions/setup-node@v6

            - name: Install app
              run: npm ci
            
            # - name: Test app
            #   run: npm test
        

    